### ISSUE TITLE
CRAN release?

### ISSUE THREAD

**Issue by b-rodrigues** [jonocarroll/ntfy#16]
Do you plan to release this package on CRAN? I think it would be a great addition!

**Comment by thomascwells** [comment]
I agree! 

I've been using helper functions built on top of this in "production"  for many months, and it's been a huge benefit to me. It's amazing to go out for a walk while waiting on some long running, but variable length, code execution.

**Comment by jonocarroll** [comment]
Thank you both for the vote of confidence in this package. I'm happy with the functionality and glad that it's able to support your use cases. I am somewhat jaded by the CRAN process, particularly when involving network-related tests. I am yet to complete some overdue maintenance of my current CRAN packages (which arose because of a change in requirements) as it is.

(I think) I've added this package to my r-universe packages https://jonocarroll.r-universe.dev/packages and am interested in what advantage you see in having the package on CRAN. I appreciate and understand the benefit of CRAN's library-wide checks, but this package only depends on httr2 and jsonlite, and due to the network-dependent nature of this package's functionality, I would most likely need to either devote a reasonable amount of effort towards robust testing (of an API over which I have no control) or use very few tests (largely defeating the purpose of library-wide testing).

That's not to say "no", but more "first, why?"

**Comment by HenrikBengtsson** [comment]
Sorry to hear about your CRAN experience.

>  I've added this package to my r-universe packages https://jonocarroll.r-universe.dev/packages and am interested in what advantage you see in having the package on CRAN.

I'd love to add a `handler_nfty()` to **progressr** for reporting of progress via **nfty**, but I can only do that reliably if not on CRAN.

If you want to avoid unit test issue due to network glitches, etc., I'd say, just add minimal tests that do not use the network.

**Comment by jonocarroll** [comment]
In that case, yes, I'll prepare for a CRAN submission, albeit without network-related tests. 

If you have noticed any inconsistencies or failures while trying out the package, please bring them to my attention.

**Comment by HenrikBengtsson** [comment]
Awesome. FYI, I've prototyped an ntfy handler for **progressr**; https://progressr.futureverse.org/reference/handler_ntfy.html.  It's actually now on CRAN, but I had to "hide" its dependency on **ntfy** for now.

**Comment by jonocarroll** [comment]
Very cool! I will aim to get a CRAN version available as soon as I can.

**Comment by jonocarroll** [comment]
@HenrikBengtsson I've pushed a new version to the `cran_release` branch which passes all checks (with `NOT_CRAN=FALSE`) locally, but it appears I can't use rhubv2 to test because I can't set that flag there. 

I did some of my own testing with your default branch (0.15.0.9000) and this example appears to work

```r
handlers("ntfy")
with_progress({ y <- slow_sum(1:10) })
```

though I only get notifications for 0%, 10%, and 100%, even with a longer `delay` set - is that expected?

I will submit this version to winbuilder then CRAN to run it through their testing suite, but if there's anything you can spot that needs fixing for compatibility please let me know.

**Comment by HenrikBengtsson** [comment]
> though I only get notifications for 0%, 10%, and 100%, even with a longer delay set - is that expected?

Yes. Each handler has an "intrusiveness" parameter associated with it. It controls how frequently progress updates are relayed to the progress reporter.  

For some types of handlers (aka "reporters") the intrusiveness is low (`intrusiveness = 1.0`), e.g. we can update a progress bar frequently without disturbing the user.  For other types, the intrusiveness is very large (`intrusiveness = 5.0`), e.g. an auditory progress reporter should not make sounds too often, because that adds a lot of disturbance and friction.  For the 'ntfy' handler, which generates notifications on smart phones, etc., I set the default to be `intrusiveness = 5.0`  (I just realized we might want to use 10.0 for notification systems).

So,  if you try with:

```sh
library(progressr)
handlers(global = TRUE)
handlers(handler_ntfy(intrusiveness = 1.0))
with_progress({ y <- slow_sum(1:10) })
```

you'll get more notifications.

PS. I'm also thinking whether there should be ways to also control the actual frequency, e.g. maximum one notification per 30 seconds.  One could also imagine an agile approach, where it will slow down the number of notifications, if it predicts the current rate will produce thousands of notifications before it reaches 100%.  So, some of this is very early days and we'll have to explore what's the best approach.

**Comment by jonocarroll** [comment]
Yep, that worked with all messages coming through. I believe the rest of that handling is on the {progressr} side so I'll finish up testing, merge, and submit.

**Comment by jonocarroll** [comment]
https://cran.r-project.org/package=ntfy 🎉

**Comment by HenrikBengtsson** [comment]
Perfect. progressr tweaked accordingly (https://github.com/futureverse/progressr/commit/95e42cd42176b09085527443d4afd9ee5af0f8d9)
